### ISSUE TITLE
failures on new image build

### ISSUE THREAD

**Issue by gonjumixproject** [QXIP/node-webshark#11]
i observe dependency failures during the new image build and i am failing to run the image due to node-fetch errors. 

can you pls help to update the Dockerfile for new builds? (newbie here)

**Comment by lmangani** [comment]
@gonjumixproject please post your errors if you'd like any type of help

**Comment by gonjumixproject** [comment]
Sorry for the delayed answer. 

I have issues on step 23 while building the image;

```
/home/node-webshark# docker build -t mytest .

...
Step 23/27 : RUN npm install && npm audit fix
 ---> Running in dfe6d6cd4558
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for express-fileupload@1.3.1: wanted: {"node":">=12.0.0"} (current: {"node":"10.24.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: express-fileupload@1.3.1
npm WARN webshark-api@1.0.2 No repository field.
npm WARN webshark-api@1.0.2 license should be a valid SPDX license expression

added 503 packages from 326 contributors and audited 505 packages in 15.959s

9 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (2 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN webshark-api@1.0.2 No repository field.
npm WARN webshark-api@1.0.2 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 3.138s

9 packages are looking for funding
  run `npm fund` for details

fixed 0 of 5 vulnerabilities in 505 scanned packages
  3 package updates for 5 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
Removing intermediate container dfe6d6cd4558
 ---> 557d98f6dd78

```

And I ve got below error when i try to run the image;
```
/home/node-webshark#  docker run -ti --rm -p 8085:8085 -v $(pwd)/captures:/captures mytest

> webshark-api@1.0.2 start /usr/src/node-webshark/api
> npx fastify start -l info app.js -p 8085

assert.js:738
    throw newErr;
    ^

AssertionError [ERR_ASSERTION]: ifError got unwanted exception: Unexpected identifier at /usr/src/node-webshark/api/node_modules/node-fetch/src/index.js:9
    at wrap (/usr/src/node-webshark/api/node_modules/fastify-cli/start.js:132:5)
    at ready.err (/usr/src/node-webshark/api/node_modules/fastify/lib/server.js:130:31)
    at manageErr (/usr/src/node-webshark/api/node_modules/fastify/fastify.js:414:11)
    at fastify.(anonymous function) (/usr/src/node-webshark/api/node_modules/fastify/fastify.js:403:11)
    at Object._encapsulateThreeParam (/usr/src/node-webshark/api/node_modules/avvio/boot.js:468:7)
    at Boot.timeoutCall (/usr/src/node-webshark/api/node_modules/avvio/boot.js:379:5)
    at Boot.callWithCbOrNextTick (/usr/src/node-webshark/api/node_modules/avvio/boot.js:360:19)
    at release (/usr/src/node-webshark/api/node_modules/fastq/queue.js:149:16)
    at Object.resume (/usr/src/node-webshark/api/node_modules/fastq/queue.js:82:7)
    at Boot.Plugin.loadPlugin.call (/usr/src/node-webshark/api/node_modules/avvio/boot.js:161:18)
import http from 'node:http';
       ^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/node-webshark/api/services/root.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webshark-api@1.0.2 start: `npx fastify start -l info app.js -p 8085`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webshark-api@1.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-23T05_55_03_068Z-debug.log

```

**Comment by lmangani** [comment]
Are you really using node version 10.24.1?

**Comment by lmangani** [comment]
does it work when using the public `qxip/webshark`?

**Comment by gonjumixproject** [comment]
yes it works when using the public qxip/webshark

**Comment by gonjumixproject** [comment]
do you think is it platform related or because of some updates on node-fetch?

**Comment by NabaragRebaca** [comment]
I had to add node-fetch too in package.json and it solved the issue. By the way @lmangani  thanks for the update of package.json.
