### ISSUE TITLE
Error trying to connect to /var/run/sharkd.sock

### ISSUE THREAD

**Issue by gonjumixproject** [QXIP/node-webshark#12]
I observe below error while launching to the application.
Can you please help me on this error if possible ?
```
{"level":30,"time":1653552495131,"pid":18,"hostname":"7172137743c7","reqId":9,"req":{"method":"GET","url":"/webshark/json?req=info","hostname":"xxx:8085","remoteAddress":"xxx","remotePort":39129},"msg":"incoming request","v":1}

Error trying to connect to /var/run/sharkd.sock
{ Error: connect ENOENT /var/run/sharkd.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/sharkd.sock' }
Trying to spawn unix:/var/run/sharkd.sock
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn sharkd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webshark-api@1.0.2 start: `npx fastify start -l info app.js -p 8085`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webshark-api@1.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-26T08_08_15_179Z-debug.log
```

**Comment by lmangani** [comment]
The error is pretty explicit

> Error trying to connect to /var/run/sharkd.sock

sharkd is not running and/or reachable by the application

**Comment by gonjumixproject** [comment]
Yes, thank you for the response. 
I am trying to understand what i am doing wrong since it is perfectly working with qxip/webshark image but fails if i build a new image.

**Comment by NabaragRebaca** [comment]
I have ran into same issue. Can't make sharkd run properly in local env though it is working with qxip/webshark image. @gonjumixproject  did you figured out the issue?

**Comment by lmangani** [comment]
Check this API fix out https://github.com/QXIP/node-webshark/commit/d397483b7eeeeeea09779692544485a19e77f0cd
Building and running sharkd is totally up to you.
